package dhcp_tile_pkg;
    import beehive_udp_msg::*;
    `include "packet_defs.vh"
    `include "noc_defs.vh"

    // DHCP well-known ports for client mode.
    localparam logic [`PORT_NUM_W-1:0] DHCP_SERVER_PORT = 16'd67;
    localparam logic [`PORT_NUM_W-1:0] DHCP_CLIENT_PORT = 16'd68;

    // DHCP-internal NoC msg types pushed by the lease FSM to subscribers
    // when the lease binds / expires. Tile-local for now -- consumers
    // (IP RX/TX tiles) are out of scope until they're updated to listen.
    localparam [`MSG_TYPE_WIDTH-1:0] DHCP_IP_BIND   = `MSG_TYPE_WIDTH'd64;
    localparam [`MSG_TYPE_WIDTH-1:0] DHCP_IP_EXPIRE = `MSG_TYPE_WIDTH'd65;

    // Current packet sizes generated by this client.
    localparam int unsigned DHCP_MIN_PAYLOAD_BYTES = 253;
    localparam int unsigned DHCP_REQUEST_PAYLOAD_BYTES = 265;
    localparam int unsigned DHCP_RETRANSMIT_SEC = 5;

    localparam int unsigned DHCP_TIMESTAMP_W = 64;
    localparam int unsigned DHCP_LEASE_SECS_W = `IP_ADDR_W;

    typedef enum logic [2:0] {
        INIT = 3'd0,
        SELECTING = 3'd1,
        REQUESTING = 3'd2,
        BOUND = 3'd3,
        RENEWING = 3'd4,
        REBINDING = 3'd5,
        UND_STATE = 'X
    } dhcp_client_state_e;

    typedef enum logic [1:0] {
        DISCOVER = 2'd0,
        REQUEST_INIT = 2'd1,
        REQUEST_RENEW = 2'd2,
        UND_TX = 'X
    } dhcp_tx_msg_type_e;

    typedef enum logic [1:0] {
        HDR_FLIT = 2'd0,
        META_FLIT = 2'd1,
        DATA_FLITS = 2'd2,
        UND_MUX = 'X
    } dhcp_out_mux_sel_e;

    typedef struct packed {
        logic [`IP_ADDR_W-1:0] yiaddr;
        logic [`IP_ADDR_W-1:0] siaddr;
        logic [DHCP_LEASE_SECS_W-1:0] lease_seconds;
        logic [DHCP_TIMESTAMP_W-1:0] lease_end_time;
        logic [DHCP_TIMESTAMP_W-1:0] t1_time;
        logic [DHCP_TIMESTAMP_W-1:0] t2_time;
        logic valid;
    } dhcp_lease_state_s;
endpackage
